networks:
  default:
    external: false
    ipam:
      driver: default
      config:
        - subnet: 172.118.0.0/16
          ip_range: 172.118.0.0/16
          gateway: 172.118.0.254
services:
  gbcs:
    build:
      context: .
    container_name: gbcs
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:13080"
      - "[::1]:8080:13080"
    depends_on:
      memcached:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "2.00"
          memory: 256M
  memcached:
    image: memcached
    container_name: memcached
    restart: unless-stopped
    command: -I 64m -m 900m
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 1G
