name: CI
on:
  push:
    branches:
      - 'dev'
jobs:
  build:
    runs-on: woryzen
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Execute Gradle build
        run: ./gradlew build
      - name: Prepare Docker image build
        run: ./gradlew prepareDockerBuild
      - name: Get project version
        id: retrieve-version
        run: ./gradlew -q version >> "$GITHUB_OUTPUT"
      - name: Login to Gitea container registry
        uses: docker/login-action@v3
        with:
          registry: gitea.woggioni.net
          username: woggioni
          password: ${{ secrets.PUBLISHER_TOKEN }}
      -
        name: Build rbcs Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          builder: "multiplatform-builder"
          context: "docker/build/docker"
          platforms: linux/amd64,linux/arm64
          push: true
          pull: true
          tags: |
            gitea.woggioni.net/woggioni/rbcs:vanilla-dev
          target: release-vanilla
      -
        name: Build rbcs memcache Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          builder: "multiplatform-builder"
          context: "docker/build/docker"
          platforms: linux/amd64,linux/arm64
          push: true
          pull: true
          tags: |
            gitea.woggioni.net/woggioni/rbcs:memcache-dev
          target: release-memcache
      -
        name: Build rbcs native Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          builder: "multiplatform-builder"
          context: "docker/build/docker"
          platforms: linux/amd64
          push: true
          pull: true
          tags: |
            gitea.woggioni.net/woggioni/rbcs:native-dev
          target: release-native
      -
        name: Build rbcs jlink Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          builder: "multiplatform-builder"
          context: "docker/build/docker"
          platforms: linux/amd64
          push: true
          pull: true
          tags: |
            gitea.woggioni.net/woggioni/rbcs:jlink-dev
          target: release-jlink

