Args=-O3 \
   -march=x86-64-v3 \
   --gc=serial \
   --enable-url-protocols=jpms \
   --pgo=conf/default.iprof \
   --initialize-at-run-time=io.netty \
   --initialize-at-build-time=net.woggioni.rbcs.common.RbcsUrlStreamHandlerFactory,net.woggioni.rbcs.common.RbcsUrlStreamHandlerFactory$JpmsHandler \
   --trace-object-instantiation=ch.qos.logback.classic.Logger \
   -H:+UnlockExperimentalVMOptions \
   -H:+SharedArenaSupport
#-H:TraceClassInitialization=io.netty.handler.ssl.BouncyCastleAlpnSslUtils